# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: changelog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='changelog.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x63hangelog.proto\"\x0c\n\nLogRequest\"\x1e\n\x0bLogResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t27\n\x10\x43hangeLogService\x12#\n\x06getLog\x12\x0b.LogRequest\x1a\x0c.LogResponseb\x06proto3')
)




_LOGREQUEST = _descriptor.Descriptor(
  name='LogRequest',
  full_name='LogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=31,
)


_LOGRESPONSE = _descriptor.Descriptor(
  name='LogResponse',
  full_name='LogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='LogResponse.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['LogRequest'] = _LOGREQUEST
DESCRIPTOR.message_types_by_name['LogResponse'] = _LOGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogRequest = _reflection.GeneratedProtocolMessageType('LogRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGREQUEST,
  __module__ = 'changelog_pb2'
  # @@protoc_insertion_point(class_scope:LogRequest)
  ))
_sym_db.RegisterMessage(LogRequest)

LogResponse = _reflection.GeneratedProtocolMessageType('LogResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGRESPONSE,
  __module__ = 'changelog_pb2'
  # @@protoc_insertion_point(class_scope:LogResponse)
  ))
_sym_db.RegisterMessage(LogResponse)



_CHANGELOGSERVICE = _descriptor.ServiceDescriptor(
  name='ChangeLogService',
  full_name='ChangeLogService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=65,
  serialized_end=120,
  methods=[
  _descriptor.MethodDescriptor(
    name='getLog',
    full_name='ChangeLogService.getLog',
    index=0,
    containing_service=None,
    input_type=_LOGREQUEST,
    output_type=_LOGRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHANGELOGSERVICE)

DESCRIPTOR.services_by_name['ChangeLogService'] = _CHANGELOGSERVICE

# @@protoc_insertion_point(module_scope)
