# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import autogen.changelog_pb2 as changelog__pb2


class ChangeLogServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getLog = channel.unary_unary(
        '/ChangeLogService/getLog',
        request_serializer=changelog__pb2.LogRequest.SerializeToString,
        response_deserializer=changelog__pb2.LogResponse.FromString,
        )


class ChangeLogServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getLog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChangeLogServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getLog': grpc.unary_unary_rpc_method_handler(
          servicer.getLog,
          request_deserializer=changelog__pb2.LogRequest.FromString,
          response_serializer=changelog__pb2.LogResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ChangeLogService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
